version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
    networks:
      - bridge

  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    image: application
    depends_on:
      postgres:
        condition: "service_healthy"
    environment:
      CONFIG_PATH: ./local.yaml
    ports:
      - "1111:1111"
    networks:
      - bridge

volumes:
  postgres:

networks:
  bridge: