swagger: "2.0"
info:
  title: VK test task service
  description: specification for VK test task service
  version: 0.0.1
host:
  localhost
schemes:
  - http
  - https
basePath: /

paths:
  /auth/sign-up:
    post:
      tags:
        - auth
      summary: sign-up for new user
      operationId: register
      parameters:
        - in: body
          name: registerUser
          description: The user for register
          schema:
            $ref: '#/definitions/UserSignUp'
      responses:
        200:
          description: OK
        400:
          description: Bad request
        500:
          description: Internal error
  /auth/sign-in:
    post:
      tags:
        - auth
      summary: sign-in for user
      operationId: login
      parameters:
        - in: body
          name: loginUser
          description: The user for login
          schema:
            $ref: '#/definitions/UserSignIn'
      responses:
        200:
          description: OK
        400:
          description: Bad request
        500:
          description: Internal error
  /api/v1/actor/create:
    post:
      tags:
        - actor
      summary: add a new actor
      operationId: createActor
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: createActor
          description: The actor to create
          schema:
            $ref: '#/definitions/GetActor'
      responses:
        200:
          description: OK
        400:
          description: Bad request
        500:
          description: Internal error
  /api/v1/actor/update:
    put:
      tags:
        - actor
      summary: updating actor's information
      operationId: updateActor
      parameters:
        - in: body
          name: updateActor
          description: The body of updating actor
          schema:
            $ref: '#/definitions/UpdateActor'
      responses:
        200:
          description: OK
        400:
          description: Bad request
        404:
          description: Not found actor
        500:
          description: Internal error
  /api/v1/actor/delete/{id}:
    delete:
      tags:
        - actor
      summary: deleting actor
      operationId: deleteActor
      parameters:
        - name: id
          in: path
          description: ID of deleting actor
          type: integer
          required: true
      responses:
        200:
          description: OK
        400:
          description: Bad request
        404:
          description: Not found actor
        500:
          description: Internal error
  /api/v1/film/create:
    post:
      tags:
        - film
      summary: add a new film
      operationId: createFilm
      parameters:
        - in: body
          name: createFilm
          description: The film to create
          schema:
            $ref: '#/definitions/Film'
      responses:
        200:
          description: OK
        400:
          description: Bad request
        500:
          description: Internal error
  /api/v1/film/update:
    put:
      tags:
        - film
      summary: updating film's information
      operationId: updateFilm
      parameters:
        - in: body
          name: updateFilm
          description: The body of updating film
          schema:
            $ref: '#/definitions/UpdateFilm'
      responses:
        200:
          description: OK
        400:
          description: Bad request
        404:
          description: Not found actor
        500:
          description: Internal error
  /api/v1/film/delete/{id}:
    delete:
      tags:
        - film
      summary: deleting film
      operationId: deleteFilm
      parameters:
        - name: id
          in: path
          description: ID of deleting film
          type: integer
          required: true
      responses:
        200:
          description: OK
        400:
          description: Bad request
        404:
          description: Not found actor
        500:
          description: Internal error
  /api/v1/films/{sortby}:
    get:
      tags:
        - film
      summary: getting films, sorting by (rating, name, date)
      operationId: films
      parameters:
        - name: sortby
          in: path
          description: sort by which param
          type: string
          required: true
          default: rating
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Film'
        500:
          description: Internal error
  /api/v1/films/name/{name}:
    get:
      tags:
        - film
      summary: getting films by fragment of name
      operationId: filmsByName
      parameters:
        - name: name
          in: path
          description: name fragment of film
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Film'
        500:
          description: Internal error
  /api/v1/films/actor/{name}:
    get:
      tags:
        - film
      summary: getting films by fragment of actor's name
      operationId: filmsByActor
      parameters:
        - name: name
          in: path
          description: actor's name fragment of film
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Film'
        500:
          description: Internal error
  /api/v1/actors:
    get:
      tags:
        - actor
      summary: getting actors and films with them
      operationId: actorsWithFilms
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ActorsWithFilms'
        500:
          description: Internal error

definitions:
  UserSignUp:
    properties:
      email:
        type: string
      password:
        type: string
      role:
        type: string
    required:
      - email
      - password
      - role
  UserSignIn:
    properties:
      email:
        type: string
      password:
        type: string
    required:
      - email
      - password
  GetActor:
    properties:
      name:
        type: string
      sex:
        type: string
      birthday:
        type: string
        format: date
    required:
      - name
      - sex
      - birthday
  UpdateActor:
    properties:
      name:
        type: string
      sex:
        type: string
      birthday:
        type: string
        format: date
  Film:
    properties:
      name:
        type: string
        minLength: 1
        maxLength: 150
      description:
        type: string
        maxLength: 1000
      date:
        type: string
        format: date
      rating:
        type: integer
        minimum: 0
        maximum: 10
      actors:
        type: array
        items:
          type: string
    required:
      - name
      - date
      - rating
      - actors
  UpdateFilm:
    properties:
      name:
        type: string
        minLength: 1
        maxLength: 150
      description:
        type: string
        maxLength: 1000
      date:
        type: string
        format: date
      rating:
        type: integer
        minimum: 0
        maximum: 10
      actors:
        type: array
        items:
          type: string
  ActorsWithFilms:
    properties:
      name:
        type: string
      sex:
        type: string
      birthday:
        type: string
        format: date
      films:
        type: array
        items:
          type: string