swagger: "2.0"
info:
  title: VK test task service
  description: specification for VK test task service
  version: 0.0.1
host:
  localhost
schemes:
  - http
  - https
basePath: /

paths:
  /auth/sign-up:
    post:
      tags:
        - auth
      summary: sign-up for new user
      operationId: register
      parameters:
        - in: body
          name: registerUser
          description: The user for register
          schema:
            $ref: '#/definition/UserSignUp'
      responses:
        200:
          description: OK
        400:
          description: Bad request
        500:
          description: Internal error
  /auth/sign-in:
    post:
      tags:
        - auth
      summary: sign-in for user
      operationId: login
      parameters:
        - in: body
          name: loginUser
          description: The user for login
          schema:
            $ref: '#/definition/UserSignIn'
  /api/v1/actor/create:
    post:
      tags:
        - actor
      summary: add a new actor
      operationId: createActor
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: createActor
          description: The actor to create
          schema:
            $ref: '#/definitions/GetActor'
      responses:
        200:
          description: OK
        400:
          description: Bad request
        500:
          description: Internal error
  /api/v1/actor/update:
    put:
      tags:
        - actor
      summary: updating actor's information
      operationId: updateActor
      parameters:
        - in: body
          name: updateActor
          description: The body of updating actor
          schema:
            $ref: '#/definitions/UpdateActor'
      responses:
        200:
          description: OK
        400:
          description: Bad request
        404:
          description: Not found actor
        500:
          description: Internal error
  /api/v1/actor/delete/{id}:
    delete:
      tags:
        - actor
      summary: deleting actor
      operationId: deleteActor
      parameters:
        - name: id
          in: path
          description: ID of deleting actor
          type: integer
          required: true
      responses:
        200:
          description: OK
        400:
          description: Bad request
        404:
          description: Not found actor
        500:
          description: Internal error
  /api/v1/film/create:
    post:
      tags:
        - film
      summary: add a new film
      operationId: createFilm
      parameters:
        - in: body
          name: createFilm
          description: The film to create
          schema:
            $ref: '#/definitions/Film'
      responses:
        200:
          description: OK
        400:
          description: Bad request
        500:
          description: Internal error

definitions:
  UserSignUp:
    properties:
      email:
        type: string
      password:
        type: string
      role:
        type: string
  UserSignIn:
    properties:
      email:
        type: string
      password:
        type: string
  GetActor:
    properties:
      name:
        type: string
      sex:
        type: string
      birthday:
        type: string
        format: date
    required:
      - name
      - sex
      - birthday
  UpdateActor:
    properties:
      name:
        type: string
      sex:
        type: string
      birthday:
        type: string
        format: date
  Film:
    properties:
      name:
        type: string
        minLength: 1
        maxLength: 150
      description:
        type: string
        maxLength: 1000
      date:
        type: string
        format: date
      rating:
        type: integer
        minimum: 0
        maximum: 10
      actors:
        allOf:
          - type: string